const CONFIG = {
  HEXO_HOME_BANNER_ENABLE: true,
  HEXO_HOME_BANNER_GREETINGS: [
    'Hi，我是一个程序员',
    'Hi，我是一个打工人',
    'Hi，我是一个干饭人',
    '欢迎来到我的博客🎉'
  ],

  HEXO_HOME_NAV_BUTTONS: true,
  HEXO_HOME_NAV_BACKGROUND_IMG_FIXED: false,
  HEXO_SHOW_START_READING: true,

  HEXO_MENU_INDEX: true,
  HEXO_MENU_CATEGORY: true,
  HEXO_MENU_TAG: true,
  HEXO_MENU_ARCHIVE: true,
  HEXO_MENU_SEARCH: true,
  HEXO_MENU_RANDOM: true,

  HEXO_POST_LIST_COVER: true,
  HEXO_POST_LIST_COVER_HOVER_ENLARGE: false,
  HEXO_POST_LIST_COVER_DEFAULT: true,
  HEXO_POST_LIST_SUMMARY: true,
  HEXO_POST_LIST_PREVIEW: false,
  HEXO_POST_LIST_IMG_CROSSOVER: true,

  HEXO_ARTICLE_ADJACENT: true,
  HEXO_ARTICLE_COPYRIGHT: true,
  HEXO_ARTICLE_NOT_BY_AI: false,
  HEXO_ARTICLE_RECOMMEND: true,

  HEXO_WIDGET_LATEST_POSTS: true,
  // 显示文章数、总访问量和独立访客数。
  HEXO_WIDGET_ANALYTICS: true,
  HEXO_WIDGET_TO_TOP: true,
  HEXO_WIDGET_TO_COMMENT: true,
  HEXO_WIDGET_DARK_MODE: true,
  HEXO_WIDGET_TOC: true,

  HEXO_COLOR_PRIMARY: '#928CEE',
  HEXO_THEME_COLOR: '#928CEE',
  HEXO_ARTICLE_ROUTE_LOADING: true
}
export default CONFIG
